version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "smolespi"
    default_labels:
      - "dependabot"
    commit_message:
      prefix: "chore:"
