"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true
"skip_untranslated_strings": true
"skip_untranslated_files": true
"export_only_approved": true

files: [
  {
    "source": "/locales/en-US/*.json",
    "translation": "/locales/%locale%",
  }
]
