files:
  - source: /locales/en-US/*.json
    translation: /locales/%locale%

commit_message: "i18n: new %language% translations"
append_commit_message: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
