version: "3"

services:
    db:
        image: rethinkdb
        volumes:
            - ./rethinkdb_data:/data
        restart: always
    bot:
        build: .
        environment:
            NODE_ENV: production
        ports:
            - "127.0.0.1:9099:9099"
        volumes:
            - ./config.example.js:/app/config.js
        restart: always
        depends_on: [db]

