name: Crowdin

on:
  push:
    branches: [main]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crowdin Synchronization
        uses: crowdin/github-action@1.0.13
        with:
          upload_translations: true
          download_translations: true
          commit_message: "i18n: new %language% translations"
          pull_request_title: "[i18n] New translations"
          pull_request_labels: "translations"
          pull_request_body: "New Crowdin pull request with translations"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
